
env:
   global:
     - CONAN_REFERENCE: "bzip2/1.0.6"
     - CONAN_USERNAME: "conan"
     - CONAN_CHANNEL: "release"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/ecashptyltd/public-conan"
     - CONAN_STABLE_BRANCH_PATTERN: "build-for-bintray/release/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=armv7hf
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
